# 插件主配置
config-version: 1.0
debug: true

# 胡萝卜镐配置
carrot-pickaxe:
  debug: true
  # 物品的命名空间ID (必须与ItemsAdder配置一致)
  item-id: "carrot_pickaxe"

  # 触发概率 (1-100)
  trigger-chance: 25

  # 掉落物设置
  drops:
    min: 1
    max: 3

  # 生效方块列表 (使用游戏内方块ID)
  enabled-blocks:
    - "COAL_ORE"
    - "DEEPSLATE_COAL_ORE"
    - "IRON_ORE"
    - "DEEPSLATE_IRON_ORE"
    - "GOLD_ORE"
    - "DEEPSLATE_GOLD_ORE"
    - "DIAMOND_ORE"
    - "DEEPSLATE_DIAMOND_ORE"
    - "NETHER_QUARTZ_ORE"